name: Deployment of the Accumulate Web Application API

on:
  push:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create config.env file
        run: |
          touch config/config.env
          echo MONGO_URI_TESTING=${{ secrets.MONGO_URI_TESTING }} >> config/config.env
          cat config/config.env

      - name: Delete .gitignore
        run: |
          rm .gitignore

      - name: Push config.env file to dir
        run: |
          git config user.email margaiwangara@gmail.com
          git config user.name margaiwangara
          git add .
          git commit -m 'added config.env file for testing'

      - name: Install Dependencies and Test
        run: |
          npm install
          npm test
        env:
          CI: true
          MONGO_URI_TESTING: ${{ secrets.MONGO_URI_TESTING }}

  deploy:
    needs: [test]
    name: Deploy app to ftp server
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.FTP_SERVER }}/devnewsbucket/
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
