name: Deployment of the Accumulate Web Application API

on:
  push:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies and Test
        run: |
          npm install
          npm test
        env:
          CI: true
          MONGO_URI_TESTING: ${{ secrets.MONGO_URI_TESTING }}

  deploy:
    needs: [test]
    name: Deploy app to ftp server
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: devnewsbucket/
